//go:build !ignore_autogenerated

// Hand-maintained deepcopy for EndpointExport - this repo has no codegen step.
// Keep in sync with endpointexport_types.go by hand.

package v1alpha1

import (
	mcsv1alpha1 "github.com/DataWerx/datawerx-mesh/pkg/apis/multicluster/v1alpha1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

func (in *EndpointExport) DeepCopyInto(out *EndpointExport) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
}

func (in *EndpointExport) DeepCopy() *EndpointExport {
	if in == nil {
		return nil
	}
	out := new(EndpointExport)
	in.DeepCopyInto(out)
	return out
}

func (in *EndpointExport) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *EndpointExportSpec) DeepCopyInto(out *EndpointExportSpec) {
	*out = *in
	if in.Ports != nil {
		l := make([]mcsv1alpha1.ServicePort, len(in.Ports))
		for i := range in.Ports {
			in.Ports[i].DeepCopyInto(&l[i])
		}
		out.Ports = l
	}
	if in.IPs != nil {
		out.IPs = make([]string, len(in.IPs))
		copy(out.IPs, in.IPs)
	}
}

func (in *EndpointExportSpec) DeepCopy() *EndpointExportSpec {
	if in == nil {
		return nil
	}
	out := new(EndpointExportSpec)
	in.DeepCopyInto(out)
	return out
}

func (in *EndpointExportList) DeepCopyInto(out *EndpointExportList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		l := make([]EndpointExport, len(in.Items))
		for i := range in.Items {
			in.Items[i].DeepCopyInto(&l[i])
		}
		out.Items = l
	}
}

func (in *EndpointExportList) DeepCopy() *EndpointExportList {
	if in == nil {
		return nil
	}
	out := new(EndpointExportList)
	in.DeepCopyInto(out)
	return out
}

func (in *EndpointExportList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}
