//go:build !ignore_autogenerated

// Hand-maintained deepcopy for MeshNetworkPolicy - this repo has no codegen step.
// Keep in sync with meshnetworkpolicy_types.go by hand.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

func (in *MeshNetworkPolicy) DeepCopyInto(out *MeshNetworkPolicy) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	out.Status = in.Status
}

func (in *MeshNetworkPolicy) DeepCopy() *MeshNetworkPolicy {
	if in == nil {
		return nil
	}
	out := new(MeshNetworkPolicy)
	in.DeepCopyInto(out)
	return out
}

func (in *MeshNetworkPolicy) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *MeshNetworkPolicySpec) DeepCopyInto(out *MeshNetworkPolicySpec) {
	*out = *in
	if in.Destinations != nil {
		out.Destinations = make([]string, len(in.Destinations))
		copy(out.Destinations, in.Destinations)
	}
	if in.Ingress != nil {
		l := make([]MeshIngressRule, len(in.Ingress))
		for i := range in.Ingress {
			in.Ingress[i].DeepCopyInto(&l[i])
		}
		out.Ingress = l
	}
}

func (in *MeshNetworkPolicySpec) DeepCopy() *MeshNetworkPolicySpec {
	if in == nil {
		return nil
	}
	out := new(MeshNetworkPolicySpec)
	in.DeepCopyInto(out)
	return out
}

func (in *MeshIngressRule) DeepCopyInto(out *MeshIngressRule) {
	*out = *in
	if in.From != nil {
		l := make([]MeshPeerSelector, len(in.From))
		for i := range in.From {
			in.From[i].DeepCopyInto(&l[i])
		}
		out.From = l
	}
	if in.Ports != nil {
		out.Ports = make([]MeshNetworkPolicyPort, len(in.Ports))
		copy(out.Ports, in.Ports)
	}
}

func (in *MeshIngressRule) DeepCopy() *MeshIngressRule {
	if in == nil {
		return nil
	}
	out := new(MeshIngressRule)
	in.DeepCopyInto(out)
	return out
}

func (in *MeshPeerSelector) DeepCopyInto(out *MeshPeerSelector) {
	*out = *in
	if in.ClusterIDs != nil {
		out.ClusterIDs = make([]string, len(in.ClusterIDs))
		copy(out.ClusterIDs, in.ClusterIDs)
	}
	if in.CIDRs != nil {
		out.CIDRs = make([]string, len(in.CIDRs))
		copy(out.CIDRs, in.CIDRs)
	}
}

func (in *MeshPeerSelector) DeepCopy() *MeshPeerSelector {
	if in == nil {
		return nil
	}
	out := new(MeshPeerSelector)
	in.DeepCopyInto(out)
	return out
}

func (in *MeshNetworkPolicyList) DeepCopyInto(out *MeshNetworkPolicyList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		l := make([]MeshNetworkPolicy, len(in.Items))
		for i := range in.Items {
			in.Items[i].DeepCopyInto(&l[i])
		}
		out.Items = l
	}
}

func (in *MeshNetworkPolicyList) DeepCopy() *MeshNetworkPolicyList {
	if in == nil {
		return nil
	}
	out := new(MeshNetworkPolicyList)
	in.DeepCopyInto(out)
	return out
}

func (in *MeshNetworkPolicyList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}
