//go:build !ignore_autogenerated

// Code in this file is equivalent to what `controller-gen object` would emit.
// It is hand-maintained here so that the module compiles cleanly without a
// code-generation step in CI. If you regenerate with controller-gen, this file
// will be overwritten with identical semantics.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto copies the receiver into out. in and out must be non-nil.
func (in *MeshPeer) DeepCopyInto(out *MeshPeer) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	out.Status = in.Status
}

// DeepCopy creates a new MeshPeer by deep copying the receiver.
func (in *MeshPeer) DeepCopy() *MeshPeer {
	if in == nil {
		return nil
	}
	out := new(MeshPeer)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject returns a deep copy of the receiver as a runtime.Object.
func (in *MeshPeer) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto copies the receiver into out. in and out must be non-nil.
func (in *MeshPeerList) DeepCopyInto(out *MeshPeerList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		l := make([]MeshPeer, len(in.Items))
		for i := range in.Items {
			in.Items[i].DeepCopyInto(&l[i])
		}
		out.Items = l
	}
}

// DeepCopy creates a new MeshPeerList by deep copying the receiver.
func (in *MeshPeerList) DeepCopy() *MeshPeerList {
	if in == nil {
		return nil
	}
	out := new(MeshPeerList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject returns a deep copy of the receiver as a runtime.Object.
func (in *MeshPeerList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto copies the receiver into out. in and out must be non-nil.
func (in *MeshPeerSpec) DeepCopyInto(out *MeshPeerSpec) {
	*out = *in
	if in.PodCIDRs != nil {
		out.PodCIDRs = make([]string, len(in.PodCIDRs))
		copy(out.PodCIDRs, in.PodCIDRs)
	}
	if in.ServiceCIDRs != nil {
		out.ServiceCIDRs = make([]string, len(in.ServiceCIDRs))
		copy(out.ServiceCIDRs, in.ServiceCIDRs)
	}
}

// DeepCopy creates a new MeshPeerSpec by deep copying the receiver.
func (in *MeshPeerSpec) DeepCopy() *MeshPeerSpec {
	if in == nil {
		return nil
	}
	out := new(MeshPeerSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto copies the receiver into out. in and out must be non-nil.
func (in *MeshPeerStatus) DeepCopyInto(out *MeshPeerStatus) {
	*out = *in
}

// DeepCopy creates a new MeshPeerStatus by deep copying the receiver.
func (in *MeshPeerStatus) DeepCopy() *MeshPeerStatus {
	if in == nil {
		return nil
	}
	out := new(MeshPeerStatus)
	in.DeepCopyInto(out)
	return out
}
