{{- if and (not .Values.wireguard.privateKey.existingSecret) .Values.wireguard.privateKey.value }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "datawerx-mesh.wgSecretName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "datawerx-mesh.labels" . | nindent 4 }}
type: Opaque
stringData:
  private-key: {{ .Values.wireguard.privateKey.value | quote }}
{{- end }}
